language: rust
sudo: false
language: rust

rust:
- stable
- beta
- nightly

cache:
  directories:
    - $HOME/.cargo
    - target

install:
  - true

before_script:
- |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH

env:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - TRAVIS_CARGO_NIGHTLY_FEATURE="" EXTRA='--features serde'

script:
- travis-cargo build -- $EXTRA
- travis-cargo test  -- $EXTRA

matrix:
    allow_failures:
        - rust: nightly
        - rust: beta
