language: rust
sudo: false
language: rust

rust:
- stable
- beta
- nightly

cache:
  directories:
    - $HOME/.cargo
    - target

install:
  - true

before_script:
- |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH

env:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - TRAVIS_CARGO_NIGHTLY_FEATURE="" EXTRA='--features serde' DOC=t

script:
- travis-cargo build -- $EXTRA
- travis-cargo test  -- $EXTRA
- |
    if [ "$DOC" = t ]; then travis-cargo --only stable doc; fi
after_success:
  # upload the documentation from the build with stable (automatically only actually
  # runs on the master branch, not individual PRs)
  - |
      if [ "$DOC" = t ]; then travis-cargo --only stable doc-upload; fi

matrix:
    allow_failures:
        - rust: nightly
        - rust: beta
